/**
 * Builds the object the preload exposes on `window.api`.
 *
 * Kept free of any `electron` import so it can be unit-tested directly: the
 * preload entry point supplies the real `ipcRenderer`, a test supplies a fake.
 *
 * The shape is generated by walking `REQUEST_CHANNELS`, which is what makes
 * this *not* a generic bridge. Every exposed function has its channel baked in
 * at construction time; nothing the renderer passes is ever used as a channel
 * name. There is no `invoke(channel, ...)`, no `exec`, no `shell`.
 */

import {
  EVENT_CHANNELS,
  REQUEST_CHANNELS,
  type EventChannel,
  type EventMap,
  type IpcMap,
  type IpcResult,
  type RequestChannel,
} from '../shared/ipc-contract.js';

export interface BridgeTransport {
  invoke(channel: string, payload: unknown): Promise<unknown>;
  on(channel: string, listener: (payload: unknown) => void): () => void;
}

/** Error surfaced in the renderer when the main process refuses a request. */
export class IpcError extends Error {
  constructor(
    readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = 'IpcError';
  }
}

type GroupOf<C extends string> = C extends `${infer G}.${string}` ? G : never;
type MethodOf<C extends string> = C extends `${string}.${infer M}` ? M : never;
type ChannelsIn<G extends string> = Extract<RequestChannel, `${G}.${string}`>;
type EventMethod<C extends string> = C extends `${infer N}:${infer R}`
  ? `${N}${Capitalize<R>}`
  : never;

type Api = {
  [G in GroupOf<RequestChannel>]: {
    [C in ChannelsIn<G> as MethodOf<C>]: IpcMap[C]['request'] extends void
      ? () => Promise<IpcMap[C]['response']>
      : (payload: IpcMap[C]['request']) => Promise<IpcMap[C]['response']>;
  };
} & {
  events: {
    [E in EventChannel as EventMethod<E>]: (
      listener: (payload: EventMap[E]) => void,
    ) => () => void;
  };
};

function eventMethodName(channel: EventChannel): string {
  const [group, rest] = channel.split(':') as [string, string];
  return `${group}${rest.charAt(0).toUpperCase()}${rest.slice(1)}`;
}

export function buildApi(transport: BridgeTransport): Api {
  const api: Record<string, Record<string, unknown>> = {};

  for (const channel of REQUEST_CHANNELS) {
    const [group, method] = channel.split('.') as [string, string];
    const bucket = (api[group] ??= {});
    // `channel` is captured here, never taken from the caller.
    bucket[method] = async (payload?: unknown): Promise<unknown> => {
      const result = (await transport.invoke(channel, payload ?? null)) as IpcResult<unknown>;
      if (!result || typeof result !== 'object' || !('ok' in result)) {
        throw new IpcError('MALFORMED_RESPONSE', `${channel} returned an unusable response`);
      }
      if (result.ok) return result.value;
      throw new IpcError(result.error.code, result.error.message);
    };
  }

  const events: Record<string, unknown> = {};
  for (const channel of EVENT_CHANNELS) {
    events[eventMethodName(channel)] = (listener: (payload: unknown) => void) =>
      transport.on(channel, listener);
  }
  api['events'] = events;

  return api as unknown as Api;
}

export type DesktopApi = Api;
