import {useEffect,useState} from 'react';
import {api,messageOf} from '@/lib/api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {AGENT_ROLES,DEFAULT_POLICY_CONFIGURATION,type PolicyConfiguration,type ModelPolicy,type TaskKind} from '@shared/agent-policy';
import {PolicyLayerFields} from './AgentPolicyFields';
export function ModelPoliciesCard() {
 const [agents,setAgents]=useState<import('@shared/ipc-contract').ManagedAgentView[]>([]);
 useEffect(()=>{void api.agents.manage().then(rows=>setAgents([...rows]));},[]);
 const [config,setConfig]=useState<PolicyConfiguration>(DEFAULT_POLICY_CONFIGURATION);
 const [filter,setFilter]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{void api.agents.policies().then(setConfig).catch(e=>setError(messageOf(e)));},[]);
 const update=(index:number,patch:Partial<ModelPolicy>)=>setConfig({...config,models:config.models.map((m,i)=>i===index?{...m,...patch}:m)});
 const save=async()=>{setBusy(true);try{setConfig(await api.agents.savePolicies(config));setError('Políticas salvas. Aplicadas antes da próxima chamada.');}catch(e){setError(messageOf(e));}finally{setBusy(false);}};
 return <section className="space-y-4 border-t pt-5" data-testid="model-policies"><h2 className="text-lg font-semibold">Políticas globais de modelos</h2><p className="text-sm text-muted-foreground">Bloqueios e tetos valem para supervisão, delegação, fallback e retomada. Uma permissão individual não amplia a política global.</p>
 <div className="flex gap-2"><Input placeholder="Filtrar modelo ou provedor" value={filter} onChange={e=>setFilter(e.target.value)}/><Button onClick={()=>setConfig({...config,models:[...config.models,{provider:'openai',modelId:'',allowed:true,premium:false,confirmationRequired:false,allowedRoles:[],capability:null}]})} data-testid="model-rule-add">Adicionar regra</Button></div>
 <div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr>{['Provedor','Modelo','Permitido','Premium','Confirmar','Teto do modelo','Funções permitidas',''].map((s,i)=><th className="text-left p-2" key={i}>{s}</th>)}</tr></thead><tbody>{config.models.map((m,i)=>(m.modelId+' '+m.provider).toLowerCase().includes(filter.toLowerCase())&&<tr key={i} className="border-t"><td><select aria-label="Provedor da regra" value={m.provider} onChange={e=>update(i,{provider:e.target.value as ModelPolicy['provider']})}><option>openai</option><option>anthropic</option></select></td><td><Input aria-label="Modelo da regra" value={m.modelId} onChange={e=>update(i,{modelId:e.target.value})}/></td>{(['allowed','premium','confirmationRequired'] as const).map(k=><td className="p-2" key={k}><input aria-label={`${k} ${m.modelId}`} type="checkbox" checked={m[k]} onChange={e=>update(i,{[k]:e.target.checked})}/></td>)}<td><select aria-label="Capacidade do modelo" value={m.capability??''} onChange={e=>update(i,{capability:e.target.value as ModelPolicy['capability']||null})}><option value="">Não informada</option>{['FAST','BALANCED','STRONG','MAX'].map(t=><option key={t}>{t}</option>)}</select></td><td><select multiple aria-label="Funções permitidas" value={m.allowedRoles} onChange={e=>update(i,{allowedRoles:[...e.target.selectedOptions].map(o=>o.value)})}>{AGENT_ROLES.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></td><td><Button variant="ghost" onClick={()=>setConfig({...config,models:config.models.filter((_,n)=>n!==i)})}>Remover</Button></td></tr>)}</tbody></table></div>
 <details><summary>Equipe padrão para novos projetos</summary><p className="text-xs text-muted-foreground">Projetos existentes mantêm a equipe atual.</p><label className="text-xs">Orquestrador<select className="block w-full p-2 border" value={config.defaultTeam?.orchestrator??''} onChange={e=>{if(!e.target.value){const next={...config};delete next.defaultTeam;setConfig(next);}else setConfig({...config,defaultTeam:{orchestrator:e.target.value,agents:config.defaultTeam?.agents??[]}});}}><option value="">Sem equipe padrão</option>{agents.filter(a=>a.enabled&&a.role==='ORCHESTRATOR').map(a=><option key={a.id} value={a.id}>{a.name} · {a.provider}</option>)}</select></label>{config.defaultTeam&&<label className="text-xs">Agentes da equipe<select multiple className="block w-full p-2 border" value={config.defaultTeam.agents} onChange={e=>setConfig({...config,defaultTeam:{...config.defaultTeam!,agents:[...e.target.selectedOptions].map(o=>o.value)}})}>{agents.filter(a=>a.enabled&&a.role!=='ORCHESTRATOR'&&a.availability!=='UNAVAILABLE').map(a=><option key={a.id} value={a.id}>{a.name} · {a.role}</option>)}</select></label>}</details>
 <h3 className="font-medium">Padrões globais</h3><PolicyLayerFields value={config.defaults} onChange={defaults=>setConfig({...config,defaults})}/>
 <h3 className="font-medium">Roteamento por tipo de tarefa</h3><div className="grid grid-cols-2 gap-3">{(['IMPLEMENTATION','CODE_REVIEW','UI_UX','TESTING','RESEARCH','IMAGE'] as TaskKind[]).map(kind=><label className="text-xs" key={kind}>{kind}<select className="block w-full rounded border bg-surface p-2" multiple value={config.routing[kind]??[]} onChange={e=>{const routing={...config.routing};const roles=[...e.target.selectedOptions].map(o=>o.value);if(roles.length)routing[kind]=roles;else delete routing[kind];setConfig({...config,routing});}}>{AGENT_ROLES.filter(r=>r.taskKinds.includes(kind)).map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label>)}</div>
 {error&&<p role="status" className="text-sm">{error}</p>}<Button data-testid="model-policies-save" disabled={busy} onClick={()=>void save()}>Salvar políticas globais</Button></section>;
}
